version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    links:
      - redis
    depends_on:
      - redis
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"